### ISSUE TITLE
Are these dotfiles same as the video from Upcase, Git Workflow's?

### ISSUE THREAD

**Issue by baojjeu** [jsteiner/dotfiles#20]
Thanks Josh! I really like your dotfiles from Upcase - Git Workflow.
![](http://i.imgur.com/C7y02Fl.png)

but after following instructions form README, I encountered some problems:

1. I got this "checked" icon even though current working directory isn't a git repository.
![](http://i.imgur.com/agVp739.png)

2. Working directory's color isn't blue.
![](http://i.imgur.com/ZPJZdFQ.png)

3. It has a "checked" icon even though there are some modified files are not staged.
![](http://i.imgur.com/RwKm5N9.png)

Do I miss something important? Or just these dotfiles not same as the video's?

Thanks in advence. 😅

**Comment by jsteiner** [comment]
Hey there! Some of your color problems are probably because you don't want to draw bold text in bright colors:

![preferences 2015-10-06 17-19-17](https://cloud.githubusercontent.com/assets/466493/10323024/8ebff1e6-6c4e-11e5-8825-cc20b39d941a.png)

The checkmark always displays, even if you aren't in a git repo. It actually isn't for git but for zsh vim mode. So, when it's a check mark you are in insert mode, but if you press escape it will become an `x` and you can use vim commands.

The branch name, on the other hand, should _only_ display in a git repo. The branch name will change color depending on the state of the working directory.

**Comment by baojjeu** [comment]
I got it, thank you! 😀
